@startmindmap
* multi-thread
*** threading.lock
*** threading.Condition
*** from queue import Queue(线程安全队列)
*** threading.Semaphore
*** threading.Event
*** ThreadPool(from multiprocessing.pool import ThreadPool)
@endmindmap