@startmindmap
* 硬件系统
** 磁盘
** 内存
** CPU
*** APIC Timer
** RTC
** 其他输入输出设备


* 系统内核
left side
** 硬件中断处理
*** 设备驱动程序
**** 设备无关软件
***** 用户进程
** 进程管理
*** 进程实例
**** 就绪态
**** 阻塞态
**** 运行态
*** 创建与销毁
*** 进程调度器
**** 进程表
**** 调度算法???
**** 线程调度器
*** 进程间通信
** 文件系统
** 设备驱动程序
*** 不同设备定义统一的接口
*** 缓冲
** IO软件系统
*** 设备无关性,采用统一命名法
*** 同步与异步
*** 数据缓冲
** IO设备管理
*** 内存映射IO
*** 端口映射IO
*** DMA(Direct memory access)
right side
** 系统调用
*** 用户层软件

@endmindmap