# This is a basic workflow to help you get started with Actions

name: Github IO Autodeploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: 3.7
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          pip3 install mkdocs
          mkdocs --version
          pip3 install mkdocs-material
          cd ..
          git clone https://github.com/zhoukaisspu/zhoukaisspu.github.io.git
          git config --global user.name "Kai.zhou"
          git config --global user.email "zhoukaisspu@163.com"
          cd zhoukaisspu.github.io
          git remote rm origin
          git remote add origion https://zhoukaisspu@163.com:${{ secrets.DEPLOYTOKEN }}/github.com/zhoukaisspu/zhoukaisspu.github.io.git
          mkdocs gh-deploy --config-file ../ks_blog/mkdocs.yml --remote-branch master

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
